version: "3.3"

services:
  app:
    build: ./app
    image: retool/cms:development
    env_file: .env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgres/data

volumes:
  app:
  db_data:
