version:              '3.3'

services:
  app:
    image:            retool/cms
    build:            ./app
    env_file:         .env
    restart:          always
    depends_on:
      - db
    volumes:
      - static:/usr/src/app/static
  db:
    image:            postgres:alpine
    restart:          always
    env_file:         .env
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition:    on-failure
  web:
    image:            nginx:alpine
    restart:          always
    depends_on:
      - app
    configs:
      - source:       default.conf
        target:       /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    volumes:
      - type:         volume
        source:       static
        target:       /usr/share/nginx/html
volumes:
  db_data:
  static:
configs:
  default.conf:
    external:         true

# TODO:               add adminer service for db management
