version: "3.3"

services:
  app:
    build: .
    image: retool/cms:development
    env_file: .env
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app:cached
    command: gunicorn -b :8000 app.wsgi:application
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
volumes:
  db_data:
