version:            '3.3'

services:
    app:
        image:      retool/cms:development
        build:      ./app
        env_file:   .env
        restart:    on-failure
        depends_on:
            - db
        ports:
            - 8000:8000
        deploy:
            restart_policy:
                condition: on-failure
    db:
        image: postgres:alpine
        restart: always
        env_file: .env
        volumes:
            - db_data:/var/lib/postgresql/data
        deploy:
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
    web:
        image:      retool/nginx:development
        build: .
        restart:    always
        depends_on:
            - app
        ports:
            - 80:80
        deploy:
            restart_policy:
                condition: on-failure
volumes:
    db_data:
