version:        '3.3'

services:
  web:
    image:      nginx:alpine
    depends_on:
      - app
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    volumes:
      - type:   volume
        source: static
        target: /usr/share/nginx/html
  app:
    image:      retool/cms
    env_file:   .env
    depends_on:
      - db
    volumes:
      - type:   volume
        source: static
        target: /usr/bin/app/static
  db:
    image:      postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image:      adminer
    env_file:   .env
configs:
  default.conf:
    external:   true
volumes:
  static:
  db_data:
#networks:


# TODO define 'deploy' options for services
